### ISSUE TITLE
Python3

### ISSUE THREAD

**Issue by MarijnDoeve** [minprog/programmeren-2#32]
Er staat nog overal `python` in plaats van `python3`. Op WSL wordt `python` niet herkent en op macOS krijgen we uiteraard Python 2.7 😕

@stgm

**Comment by stgm** [comment]
Waar bedoel je met overal?

**Comment by MarijnDoeve** [comment]
In ieder geval bij Mario, maar ik ga er van uit dat het bij de andere python-opdrachten ook nog niet goed is.

**Comment by stgm** [comment]
Fixed :-)
